
server:
  port: 4444
  address:
#  ssl:
#    key-store: src/main/resources/ssl/my.keystore
#    key-store-password: helloxc
spring:
  datasource:
    hikari:
      maximum-pool-size: 1000
#  profiles:
#    active: jpa
  redis:
    client-type: lettuce
#    include: service
beer:
  cheese:
    cron: 0 * * * * *
    key: MyValue
