beer:
  cheese:
    app-name: hello
server:
  port: 10000
  ssl:
    key-store: src/main/resources/ssl/my.keystore
    key-store-password: helloxc
spring:
  datasource:
    hikari:
      maximum-pool-size: 1000