server:
  port: 4444
#  ssl:
#    key-store: src/main/resources/ssl/my.keystore
#    key-store-password: helloxc
#spring:
#  task:
#    execution:
#      pool:
#        core-size:
  datasource:
    hikari:
      maximum-pool-size: 1000
  profiles:
    active: h2
  redis:
    client-type: lettuce
#    include: service
beer:
  cheese:
    cron: 0 * * * * *
    key: MyValue
