server:
  port: 51488
eureka:
  client:
    service-url:
      defaultZone: http://localhost:51477/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
